# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(551, 755)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 10, 531, 121))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 90, 51, 16))
        self.label.setObjectName("label")
        self.txtFrame = QtWidgets.QLineEdit(self.frame)
        self.txtFrame.setGeometry(QtCore.QRect(70, 90, 351, 23))
        self.txtFrame.setObjectName("txtFrame")
        self.btnDecode = QtWidgets.QPushButton(self.frame)
        self.btnDecode.setGeometry(QtCore.QRect(430, 90, 80, 23))
        self.btnDecode.setObjectName("btnDecode")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(20, 10, 461, 71))
        self.label_2.setObjectName("label_2")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(10, 160, 531, 371))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.tabeps = QtWidgets.QTabWidget(self.frame_2)
        self.tabeps.setGeometry(QtCore.QRect(0, 50, 531, 321))
        self.tabeps.setObjectName("tabeps")
        self.tabEPS = QtWidgets.QWidget()
        self.tabEPS.setObjectName("tabEPS")
        self.tableEPS = QtWidgets.QTableView(self.tabEPS)
        self.tableEPS.setGeometry(QtCore.QRect(0, 0, 531, 291))
        self.tableEPS.setObjectName("tableEPS")
        self.tabeps.addTab(self.tabEPS, "")
        self.tabOBC = QtWidgets.QWidget()
        self.tabOBC.setObjectName("tabOBC")
        self.tableOBC = QtWidgets.QTableView(self.tabOBC)
        self.tableOBC.setGeometry(QtCore.QRect(0, 0, 531, 291))
        self.tableOBC.setObjectName("tableOBC")
        self.tabeps.addTab(self.tabOBC, "")
        self.tabADCS = QtWidgets.QWidget()
        self.tabADCS.setObjectName("tabADCS")
        self.tableADCS = QtWidgets.QTableView(self.tabADCS)
        self.tableADCS.setGeometry(QtCore.QRect(0, 0, 531, 291))
        self.tableADCS.setObjectName("tableADCS")
        self.tabeps.addTab(self.tabADCS, "")
        self.tabRADIO = QtWidgets.QWidget()
        self.tabRADIO.setObjectName("tabRADIO")
        self.tableRADIO = QtWidgets.QTableView(self.tabRADIO)
        self.tableRADIO.setGeometry(QtCore.QRect(0, 0, 531, 291))
        self.tableRADIO.setObjectName("tableRADIO")
        self.tabeps.addTab(self.tabRADIO, "")
        self.tabPAYLOAD = QtWidgets.QWidget()
        self.tabPAYLOAD.setObjectName("tabPAYLOAD")
        self.tablePAYLOAD = QtWidgets.QTableView(self.tabPAYLOAD)
        self.tablePAYLOAD.setGeometry(QtCore.QRect(0, 0, 531, 291))
        self.tablePAYLOAD.setObjectName("tablePAYLOAD")
        self.tabeps.addTab(self.tabPAYLOAD, "")
        self.lblStatus = QtWidgets.QLabel(self.frame_2)
        self.lblStatus.setGeometry(QtCore.QRect(10, 20, 141, 16))
        self.lblStatus.setObjectName("lblStatus")
        self.lblFrameNumber = QtWidgets.QLabel(self.frame_2)
        self.lblFrameNumber.setGeometry(QtCore.QRect(418, 20, 91, 20))
        self.lblFrameNumber.setObjectName("lblFrameNumber")
        self.frmMetadata = QtWidgets.QFrame(self.centralwidget)
        self.frmMetadata.setGeometry(QtCore.QRect(10, 540, 531, 161))
        self.frmMetadata.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmMetadata.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmMetadata.setObjectName("frmMetadata")
        self.lblName = QtWidgets.QLabel(self.frmMetadata)
        self.lblName.setGeometry(QtCore.QRect(20, 68, 181, 16))
        self.lblName.setObjectName("lblName")
        self.txtObserver = QtWidgets.QLineEdit(self.frmMetadata)
        self.txtObserver.setGeometry(QtCore.QRect(200, 68, 231, 23))
        self.txtObserver.setObjectName("txtObserver")
        self.btnSend = QtWidgets.QPushButton(self.frmMetadata)
        self.btnSend.setGeometry(QtCore.QRect(440, 70, 80, 81))
        self.btnSend.setObjectName("btnSend")
        self.label_4 = QtWidgets.QLabel(self.frmMetadata)
        self.label_4.setGeometry(QtCore.QRect(20, 10, 461, 16))
        self.label_4.setObjectName("label_4")
        self.txtLocation = QtWidgets.QLineEdit(self.frmMetadata)
        self.txtLocation.setGeometry(QtCore.QRect(200, 98, 231, 23))
        self.txtLocation.setObjectName("txtLocation")
        self.lblName_2 = QtWidgets.QLabel(self.frmMetadata)
        self.lblName_2.setGeometry(QtCore.QRect(70, 98, 131, 16))
        self.lblName_2.setObjectName("lblName_2")
        self.txtContactMail = QtWidgets.QLineEdit(self.frmMetadata)
        self.txtContactMail.setGeometry(QtCore.QRect(200, 128, 231, 23))
        self.txtContactMail.setObjectName("txtContactMail")
        self.lblName_3 = QtWidgets.QLabel(self.frmMetadata)
        self.lblName_3.setGeometry(QtCore.QRect(50, 128, 151, 16))
        self.lblName_3.setObjectName("lblName_3")
        self.txtDateTime = QtWidgets.QDateTimeEdit(self.frmMetadata)
        self.txtDateTime.setGeometry(QtCore.QRect(200, 40, 194, 24))
        self.txtDateTime.setMinimumDate(QtCore.QDate(2019, 2, 18))
        self.txtDateTime.setTimeSpec(QtCore.Qt.LocalTime)
        self.txtDateTime.setObjectName("txtDateTime")
        self.lblName_4 = QtWidgets.QLabel(self.frmMetadata)
        self.lblName_4.setGeometry(QtCore.QRect(50, 40, 141, 16))
        self.lblName_4.setObjectName("lblName_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 551, 20))
        self.menubar.setObjectName("menubar")
        self.menuDecoder = QtWidgets.QMenu(self.menubar)
        self.menuDecoder.setObjectName("menuDecoder")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen_bin_file = QtWidgets.QAction(MainWindow)
        self.actionOpen_bin_file.setObjectName("actionOpen_bin_file")
        self.actionOPen_HEX_string_file = QtWidgets.QAction(MainWindow)
        self.actionOPen_HEX_string_file.setObjectName("actionOPen_HEX_string_file")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuDecoder.addAction(self.actionOpen_bin_file)
        self.menuDecoder.addAction(self.actionOPen_HEX_string_file)
        self.menuDecoder.addSeparator()
        self.menuDecoder.addAction(self.actionExit)
        self.menu.addAction(self.actionAbout)
        self.menubar.addAction(self.menuDecoder.menuAction())
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.tabeps.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AztechSat-1 telemetry decoder"))
        self.label.setText(_translate("MainWindow", "Frame:"))
        self.btnDecode.setText(_translate("MainWindow", "DECODE"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p>Insert the data frame you want to decode in the input box below, <br>then click on Decode.<br><br>The frame must be on HEX string format. ej: (C0 00 30 80 C2 . . .)</p></body></html>"))
        self.tabeps.setTabText(self.tabeps.indexOf(self.tabEPS), _translate("MainWindow", "EPS"))
        self.tabeps.setTabText(self.tabeps.indexOf(self.tabOBC), _translate("MainWindow", "OBC"))
        self.tabeps.setTabText(self.tabeps.indexOf(self.tabADCS), _translate("MainWindow", "ADCS"))
        self.tabeps.setTabText(self.tabeps.indexOf(self.tabRADIO), _translate("MainWindow", "RADIO"))
        self.tabeps.setTabText(self.tabeps.indexOf(self.tabPAYLOAD), _translate("MainWindow", "PAYLOAD"))
        self.lblStatus.setText(_translate("MainWindow", "No data!"))
        self.lblFrameNumber.setText(_translate("MainWindow", "No data!"))
        self.lblName.setText(_translate("MainWindow", "Observer (name or callsign):"))
        self.btnSend.setText(_translate("MainWindow", "SEND"))
        self.label_4.setText(_translate("MainWindow", "Share your capture with us!"))
        self.lblName_2.setText(_translate("MainWindow", "Location (optional) :"))
        self.lblName_3.setText(_translate("MainWindow", "Contact mail (optional):"))
        self.txtDateTime.setDisplayFormat(_translate("MainWindow", "M/d/yyyy h:mm:ss AP"))
        self.lblName_4.setText(_translate("MainWindow", "Capture Date & Time :"))
        self.menuDecoder.setTitle(_translate("MainWindow", "Decoder"))
        self.menu.setTitle(_translate("MainWindow", "?"))
        self.actionOpen_bin_file.setText(_translate("MainWindow", "Open bin file ..."))
        self.actionOPen_HEX_string_file.setText(_translate("MainWindow", "Open HEX string file ..."))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionAbout.setText(_translate("MainWindow", "About"))

